### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wsor4035** [minetest/dev.luanti.org#113]
# Roadmap
- [x] (Short term) Migrate Dev Wiki content
- [ ] (Immediate) Site notice to users of WIP project state and mission statement and roadmap (#71)
- [ ] (Short term) Migrate relevant Player Wiki content (#15, #32)
- [ ] (Short term) Categorize information by target audience (API users, engine developers, server owners, players, etc.)
- [ ] (Short term) Set contribution guidelines (#60)
- [x] (Medium term) Develop build workflows (#73, might be changes later)
- [ ] (Medium term) Improve site theme and accessibility (#72, others)
- [ ] (Long term) Refocus and continue API reference efforts
- [ ] (Long term) Once proven successful, introduce LDoc annotations to the engine (this is a Docs Team job)

*originally taken from https://github.com/minetest/dev.luanti.org/issues/64*
