### ISSUE TITLE
Match lua_api.txt coverage (mega tracker)

### ISSUE THREAD

**Issue by GreenXenith** [minetest/dev.luanti.org#47]
## Namespaces
<details><summary><code>minetest</code></summary>

- [ ] `minetest.add_entity`
- [ ] `minetest.add_item`
- [ ] `minetest.add_node_level`
- [ ] `minetest.add_node`
- [ ] `minetest.add_particle`
- [ ] `minetest.add_particlespawner`
- [x] `minetest.after`
- [ ] `minetest.auth_reload`
- [ ] `minetest.ban_player`
- [ ] `minetest.bulk_set_node`
- [ ] `minetest.calculate_knockback`
- [ ] `minetest.cancel_shutdown_requests`
- [ ] `minetest.chat_send_all`
- [ ] `minetest.chat_send_player`
- [ ] `minetest.check_for_falling`
- [ ] `minetest.check_password_entry`
- [ ] `minetest.check_player_privs`
- [ ] `minetest.check_single_for_falling`
- [ ] `minetest.clear_craft`
- [ ] `minetest.clear_objects`
- [ ] `minetest.clear_registered_biomes`
- [ ] `minetest.clear_registered_decorations`
- [ ] `minetest.clear_registered_ores`
- [ ] `minetest.clear_registered_schematics`
- [ ] `minetest.close_formspec`
- [ ] `minetest.colorize`
- [ ] `minetest.colorspec_to_bytes`
- [ ] `minetest.colorspec_to_colorstring`
- [ ] `minetest.compare_block_status`
- [ ] `minetest.compress`
- [ ] `minetest.cpdir`
- [ ] `minetest.create_detached_inventory`
- [ ] `minetest.create_schematic`
- [ ] `minetest.debug`
- [ ] `minetest.decode_base64`
- [ ] `minetest.decompress`
- [ ] `minetest.delete_area`
- [ ] `minetest.delete_particlespawner`
- [x] `minetest.deserialize`
- [ ] `minetest.dig_node`
- [ ] `minetest.dir_to_facedir`
- [ ] `minetest.dir_to_wallmounted`
- [ ] `minetest.dir_to_yaw`
- [ ] `minetest.disconnect_player`
- [ ] `minetest.do_item_eat`
- [ ] `minetest.dynamic_add_media`
- [ ] `minetest.emerge_area`
- [ ] `minetest.encode_base64`
- [ ] `minetest.encode_png`
- [ ] `minetest.explode_scrollbar_event`
- [ ] `minetest.explode_table_event`
- [ ] `minetest.explode_textlist_event`
- [ ] `minetest.facedir_to_dir`
- [ ] `minetest.find_node_near`
- [ ] `minetest.find_nodes_in_area_under_air`
- [ ] `minetest.find_nodes_in_area`
- [x] `minetest.find_nodes_with_meta`
- [ ] `minetest.find_path`
- [ ] `minetest.fix_light`
- [ ] `minetest.forceload_block`
- [ ] `minetest.forceload_free_block`
- [ ] `minetest.format_chat_message`
- [ ] `minetest.formspec_escape`
- [ ] `minetest.formspec_escape`
- [ ] `minetest.generate_decorations`
- [ ] `minetest.generate_ores`
- [ ] `minetest.get_all_craft_recipes`
- [ ] `minetest.get_artificial_light`
- [ ] `minetest.get_auth_handler`
- [ ] `minetest.get_background_escape_sequence`
- [ ] `minetest.get_ban_description`
- [ ] `minetest.get_ban_list`
- [ ] `minetest.get_biome_data`
- [ ] `minetest.get_biome_id`
- [ ] `minetest.get_biome_name`
- [ ] `minetest.get_color_escape_sequence`
- [ ] `minetest.get_connected_players`
- [ ] `minetest.get_content_id`
- [ ] `minetest.get_craft_recipe`
- [ ] `minetest.get_craft_result`
- [ ] `minetest.get_current_modname`
- [ ] `minetest.get_day_count`
- [ ] `minetest.get_decoration_id`
- [ ] `minetest.get_dig_params`
- [ ] `minetest.get_dir_list`
- [x] `minetest.get_gametime`
- [ ] `minetest.get_gen_notify`
- [ ] `minetest.get_heat`
- [ ] `minetest.get_hit_params`
- [ ] `minetest.get_humidity`
- [ ] `minetest.get_item_group`
- [ ] `minetest.get_mapgen_object`
- [ ] `minetest.get_mapgen_params`
- [ ] `minetest.get_mapgen_setting_noiseparams`
- [ ] `minetest.get_mapgen_setting`
- [x] `minetest.get_meta`
- [x] `minetest.get_mod_storage`
- [ ] `minetest.get_modnames`
- [ ] `minetest.get_modpath`
- [ ] `minetest.get_name_from_content_id`
- [ ] `minetest.get_natural_light`
- [ ] `minetest.get_node_drops`
- [ ] `minetest.get_node_group`
- [ ] `minetest.get_node_level`
- [ ] `minetest.get_node_light`
- [ ] `minetest.get_node_max_level`
- [ ] `minetest.get_node_or_nil`
- [ ] `minetest.get_node_timer`
- [ ] `minetest.get_node`
- [ ] `minetest.get_noiseparams`
- [ ] `minetest.get_objects_in_area`
- [ ] `minetest.get_objects_inside_radius`
- [ ] `minetest.get_password_hash`
- [ ] `minetest.get_player_by_name`
- [ ] `minetest.get_player_information`
- [ ] `minetest.get_player_ip`
- [ ] `minetest.get_player_privs`
- [ ] `minetest.get_pointed_thing_position`
- [ ] `minetest.get_position_from_hash`
- [ ] `minetest.get_server_max_lag`
- [ ] `minetest.get_server_status`
- [ ] `minetest.get_server_uptime`
- [ ] `minetest.get_spawn_level`
- [ ] `minetest.get_timeofday`
- [ ] `minetest.get_translator`
- [x] `minetest.get_us_time`
- [ ] `minetest.get_version`
- [ ] `minetest.get_worldpath`
- [ ] `minetest.global_exists`
- [ ] `minetest.handle_node_drops`
- [ ] `minetest.has_feature`
- [ ] `minetest.hash_node_position`
- [ ] `minetest.hud_replace_builtin`
- [x] `minetest.inventorycube`
- [ ] `minetest.is_area_protected`
- [ ] `minetest.is_colored_paramtype`
- [ ] `minetest.is_creative_enabled`
- [ ] `minetest.is_nan`
- [ ] `minetest.is_player`
- [ ] `minetest.is_protected`
- [ ] `minetest.is_singleplayer`
- [ ] `minetest.is_yes`
- [ ] `minetest.item_drop`
- [ ] `minetest.item_eat`
- [ ] `minetest.item_place_node`
- [ ] `minetest.item_place_object`
- [ ] `minetest.item_place`
- [ ] `minetest.itemstring_with_color`
- [ ] `minetest.itemstring_with_palette`
- [ ] `minetest.kick_player`
- [x] `minetest.line_of_sight`
- [ ] `minetest.load_area`
- [ ] `minetest.log`
- [ ] `minetest.mkdir`
- [ ] `minetest.mvdir`
- [ ] `minetest.node_dig`
- [ ] `minetest.node_punch`
- [ ] `minetest.notify_authentication_modified`
- [ ] `minetest.override_chatcommand`
- [ ] `minetest.override_item`
- [x] `minetest.parse_json`
- [ ] `minetest.place_node`
- [ ] `minetest.place_schematic_on_vmanip`
- [ ] `minetest.place_schematic`
- [ ] `minetest.player_exists`
- [ ] `minetest.pointed_thing_to_face_pos`
- [ ] `minetest.pos_to_string`
- [ ] `minetest.privs_to_string`
- [ ] `minetest.punch_node`
- [ ] `minetest.raillike_group`
- [ ] `minetest.read_schematic`
- [ ] `minetest.record_protection_violation`
- [ ] `minetest.register_abm`
- [ ] `minetest.register_alias_force`
- [ ] `minetest.register_alias`
- [ ] `minetest.register_allow_player_inventory_action`
- [ ] `minetest.register_authentication_handler`
- [ ] `minetest.register_biome`
- [ ] `minetest.register_can_bypass_userlimit`
- [ ] `minetest.register_chatcommand`
- [ ] `minetest.register_craft_predict`
- [ ] `minetest.register_craft`
- [ ] `minetest.register_craftitem`
- [ ] `minetest.register_decoration`
- [ ] `minetest.register_entity`
- [x] `minetest.register_globalstep`
- [ ] `minetest.register_lbm`
- [ ] `minetest.register_node`
- [ ] `minetest.register_on_auth_fail`
- [ ] `minetest.register_on_authplayer`
- [ ] `minetest.register_on_chat_message`
- [ ] `minetest.register_on_chatcommand`
- [ ] `minetest.register_on_cheat`
- [ ] `minetest.register_on_craft`
- [ ] `minetest.register_on_dieplayer`
- [ ] `minetest.register_on_dignode`
- [ ] `minetest.register_on_generated`
- [ ] `minetest.register_on_item_eat`
- [ ] `minetest.register_on_joinplayer`
- [ ] `minetest.register_on_leaveplayer`
- [ ] `minetest.register_on_liquid_transformed`
- [ ] `minetest.register_on_mods_loaded`
- [ ] `minetest.register_on_newplayer`
- [ ] `minetest.register_on_placenode`
- [ ] `minetest.register_on_player_hpchange`
- [ ] `minetest.register_on_player_inventory_action`
- [ ] `minetest.register_on_player_receive_fields`
- [ ] `minetest.register_on_prejoinplayer`
- [ ] `minetest.register_on_priv_grant`
- [ ] `minetest.register_on_priv_revoke`
- [ ] `minetest.register_on_protection_violation`
- [ ] `minetest.register_on_punchnode`
- [ ] `minetest.register_on_punchplayer`
- [ ] `minetest.register_on_respawnplayer`
- [ ] `minetest.register_on_rightclickplayer`
- [ ] `minetest.register_on_shutdown`
- [ ] `minetest.register_ore`
- [ ] `minetest.register_privilege`
- [ ] `minetest.register_schematic`
- [ ] `minetest.register_tool`
- [ ] `minetest.remove_detached_inventory`
- [ ] `minetest.remove_node`
- [ ] `minetest.remove_player_auth`
- [ ] `minetest.remove_player`
- [ ] `minetest.request_insecure_environment`
- [ ] `minetest.request_shutdown`
- [ ] `minetest.rgba`
- [ ] `minetest.rmdir`
- [ ] `minetest.rollback_get_node_actions`
- [ ] `minetest.rollback_revert_actions_by`
- [ ] `minetest.rotate_and_place`
- [ ] `minetest.rotate_node`
- [ ] `minetest.safe_file_write`
- [ ] `minetest.send_join_message`
- [ ] `minetest.send_leave_message`
- [ ] `minetest.serialize_schematic`
- [x] `minetest.serialize`
- [ ] `minetest.set_gen_notify`
- [ ] `minetest.set_mapgen_params`
- [ ] `minetest.set_mapgen_setting_noiseparams`
- [ ] `minetest.set_mapgen_setting`
- [ ] `minetest.set_node_level`
- [ ] `minetest.set_node`
- [ ] `minetest.set_noiseparams`
- [ ] `minetest.set_player_password`
- [ ] `minetest.set_player_privs`
- [ ] `minetest.set_timeofday`
- [ ] `minetest.setting_get_pos`
- [ ] `minetest.sha1`
- [ ] `minetest.show_formspec`
- [ ] `minetest.sound_fade`
- [ ] `minetest.sound_play`
- [ ] `minetest.sound_stop`
- [ ] `minetest.spawn_falling_node`
- [ ] `minetest.spawn_tree `
- [ ] `minetest.string_to_area`
- [ ] `minetest.string_to_pos`
- [ ] `minetest.string_to_privs`
- [ ] `minetest.strip_background_colors`
- [ ] `minetest.strip_colors`
- [ ] `minetest.strip_foreground_colors`
- [ ] `minetest.strip_param2_color`
- [ ] `minetest.swap_node`
- [ ] `minetest.transforming_liquid_add`
- [ ] `minetest.translate`
- [ ] `minetest.unban_player_or_ip`
- [ ] `minetest.unregister_biome`
- [ ] `minetest.unregister_chatcommand`
- [ ] `minetest.unregister_item`
- [ ] `minetest.wallmounted_to_dir`
- [ ] `minetest.wrap_text`
- [x] `minetest.write_json`
- [ ] `minetest.yaw_to_dir`

#### Global Tables
- [ ] `minetest.env`
- [ ] `minetest.features`
- [ ] `minetest.luaentities`
- [ ] `minetest.object_refs`
- [ ] `minetest.registered_abms`
- [ ] `minetest.registered_aliases`
- [ ] `minetest.registered_biomes`
- [ ] `minetest.registered_chatcommands`
- [ ] `minetest.registered_craftitems`
- [ ] `minetest.registered_decorations`
- [ ] `minetest.registered_entities`
- [ ] `minetest.registered_items`
- [ ] `minetest.registered_lbms`
- [ ] `minetest.registered_nodes`
- [ ] `minetest.registered_ores`
- [ ] `minetest.registered_privileges`
- [ ] `minetest.registered_schematics`
- [ ] `minetest.registered_tools`
- [ ] `minetest.settings`

#### Constants
- [ ] `minetest.CONTENT_AIR`
- [ ] `minetest.CONTENT_IGNORE`
- [ ] `minetest.CONTENT_UNKNOWN`
- [ ] `minetest.EMERGE_CANCELLED`
- [ ] `minetest.EMERGE_ERRORED`
- [ ] `minetest.EMERGE_FROM_DISK`
- [ ] `minetest.EMERGE_FROM_MEMORY`
- [ ] `minetest.EMERGE_GENERATED`
- [ ] `minetest.LIGHT_MAX`
- [ ] `minetest.PLAYER_MAX_BREATH_DEFAULT`
- [ ] `minetest.PLAYER_MAX_HP_DEFAULT`
</details>
<details><summary><code>math</code> (done)</summary>

- [x] `math.factorial`
- [x] `math.hypot`
- [x] `math.round`
- [x] `math.sign`
</details>
<details><summary><code>string</code> (done)</summary>

- [x] `string.split`
- [x] `string:trim`
</details>
<details><summary><code>table</code> (done)</summary>

- [x] `table.copy`
- [x] `table.indexof`
- [x] `table.insert_all`
- [x] `table.key_value_swap`
- [x] `table.shuffle`
</details>
<details><summary><code>vector</code> (done)</summary>

- [x] `vector.add`
- [x] `vector.angle`
- [x] `vector.apply`
- [x] `vector.combine`
- [x] `vector.check`
- [x] `vector.copy`
- [x] `vector.cross`
- [x] `vector.dir_to_rotation`
- [x] `vector.direction`
- [x] `vector.distance`
- [x] `vector.divide`
- [x] `vector.dot`
- [x] `vector.equals`
- [x] `vector.floor`
- [x] `vector.from_string`
- [x] `vector.length`
- [x] `vector.multiply`
- [x] `vector.new`
- [x] `vector.normalize`
- [x] `vector.offset`
- [x] `vector.rotate_around_axis`
- [x] `vector.rotate`
- [x] `vector.round`
- [x] `vector.sort`
- [x] `vector.subtract`
- [x] `vector.to_string`
- [x] `vector.zero`
</details>

## Methods
<details><summary><code>AreaStore</code></summary>

- [ ] `AreaStore`
- [ ] `AreaStore:from_file`
- [ ] `AreaStore:from_string`
- [ ] `AreaStore:get_area`
- [ ] `AreaStore:get_areas_for_pos`
- [ ] `AreaStore:get_areas_in_area`
- [ ] `AreaStore:insert_area`
- [ ] `AreaStore:remove_area`
- [ ] `AreaStore:reserve`
- [ ] `AreaStore:set_cache_params`
- [ ] `AreaStore:to_file`
- [ ] `AreaStore:to_string`
</details>

<details><summary><code>HTTPApi</code> (done)</summary>

- [x] `minetest.request_http_api`
- [x] `HTTPApi.fetch`
- [x] `HTTPApi.fetch_async`
- [x] `HTTPApi.fetch_async_get`
</details>

<details><summary><code>InvRef</code></summary>

- [ ] `InvRef:add_item`
- [ ] `InvRef:contains_item`
- [ ] `InvRef:get_list`
- [ ] `InvRef:get_lists`
- [ ] `InvRef:get_location`
- [ ] `InvRef:get_size`
- [ ] `InvRef:get_stack`
- [ ] `InvRef:get_width`
- [ ] `InvRef:is_empty`
- [ ] `InvRef:remove_item`
- [ ] `InvRef:room_for_item`
- [ ] `InvRef:set_list`
- [ ] `InvRef:set_lists`
- [ ] `InvRef:set_size`
- [ ] `InvRef:set_stack`
- [ ] `InvRef:set_width`
</details>

<details><summary><code>ItemStack</code> (done)</summary>

- [x] `ItemStack`
- [x] `ItemStack:add_item`
- [x] `ItemStack:add_wear`
- [x] `ItemStack:clear`
- [x] `ItemStack:get_count`
- [x] `ItemStack:get_definition`
- [x] `ItemStack:get_description`
- [x] `ItemStack:get_free_space`
- [x] `ItemStack:get_meta`
- [x] `ItemStack:get_metadata`
- [x] `ItemStack:get_name`
- [x] `ItemStack:get_short_description`
- [x] `ItemStack:get_stack_max`
- [x] `ItemStack:get_tool_capabilities`
- [x] `ItemStack:get_wear`
- [x] `ItemStack:is_empty`
- [x] `ItemStack:is_known`
- [x] `ItemStack:item_fits`
- [x] `ItemStack:peek_item`
- [x] `ItemStack:replace`
- [x] `ItemStack:set_count`
- [x] `ItemStack:set_metadata`
- [x] `ItemStack:set_name`
- [x] `ItemStack:set_wear`
- [x] `ItemStack:take_item`
- [x] `ItemStack:to_string`
- [x] `ItemStack:to_table`
</details>

<details><summary><code>ItemStackMetaRef</code> (done)</summary>

- [x] `ItemStackMetaRef:set_tool_capabilities`
</details>

<details><summary><code>MetaDataRef</code> (done)</summary>

- [x] `MetaDataRef:contains`
- [x] `MetaDataRef:equals`
- [x] `MetaDataRef:from_table`
- [x] `MetaDataRef:get_float`
- [x] `MetaDataRef:get_int`
- [x] `MetaDataRef:get_string`
- [x] `MetaDataRef:get`
- [x] `MetaDataRef:set_float`
- [x] `MetaDataRef:set_int`
- [x] `MetaDataRef:set_string`
- [x] `MetaDataRef:to_table`
</details>

<details><summary><code>ModChannel</code> (done)</summary>

- [x] `minetest.mod_channel_join`
- [x] `minetest.register_on_modchannel_message`
- [x] `ModChannel:is_writeable`
- [x] `ModChannel:leave`
- [x] `ModChannel:send_all`
</details>

<details><summary><code>NodeMetaRef</code> (done)</summary>

- [x] `NodeMetaRef:get_inventory`
- [x] `NodeMetaRef:mark_as_private`
</details>

<details><summary><code>NodeTimerRef</code></summary>

- [ ] `NodeTimerRef:get_elapsed`
- [ ] `NodeTimerRef:get_timeout`
- [ ] `NodeTimerRef:is_started`
- [ ] `NodeTimerRef:set`
- [ ] `NodeTimerRef:start`
- [ ] `NodeTimerRef:stop`
</details>

<details><summary><code>ObjectRef</code></summary>

- [ ] `ObjectRef:add_velocity`
- [ ] `ObjectRef:get_acceleration`
- [ ] `ObjectRef:get_animation`
- [ ] `ObjectRef:get_armor_groups`
- [ ] `ObjectRef:get_attach`
- [ ] `ObjectRef:get_bone_position`
- [ ] `ObjectRef:get_children`
- [ ] `ObjectRef:get_entity_name`
- [ ] `ObjectRef:get_hp`
- [ ] `ObjectRef:get_inventory`
- [ ] `ObjectRef:get_luaentity`
- [ ] `ObjectRef:get_nametag_attributes`
- [ ] `ObjectRef:get_pos`
- [ ] `ObjectRef:get_properties`
- [ ] `ObjectRef:get_rotation`
- [ ] `ObjectRef:get_staticdata`
- [ ] `ObjectRef:get_texture_mod`
- [ ] `ObjectRef:get_velocity`
- [ ] `ObjectRef:get_wield_index`
- [ ] `ObjectRef:get_wield_list`
- [ ] `ObjectRef:get_wielded_item`
- [ ] `ObjectRef:get_yaw`
- [ ] `ObjectRef:is_player`
- [ ] `ObjectRef:move_to`
- [ ] `ObjectRef:on_activate`
- [ ] `ObjectRef:on_attach_child`
- [ ] `ObjectRef:on_deactivate`
- [ ] `ObjectRef:on_death`
- [ ] `ObjectRef:on_detach_child`
- [ ] `ObjectRef:on_detach`
- [ ] `ObjectRef:on_punch`
- [ ] `ObjectRef:on_rightclick`
- [ ] `ObjectRef:on_step`
- [ ] `ObjectRef:punch`
- [ ] `ObjectRef:remove`
- [ ] `ObjectRef:right_click`
- [ ] `ObjectRef:set_acceleration`
- [ ] `ObjectRef:set_animation_frame_speed`
- [ ] `ObjectRef:set_animation`
- [ ] `ObjectRef:set_armor_groups`
- [ ] `ObjectRef:set_attach`
- [ ] `ObjectRef:set_bone_position`
- [ ] `ObjectRef:set_detach`
- [ ] `ObjectRef:set_hp`
- [ ] `ObjectRef:set_nametag_attributes`
- [ ] `ObjectRef:set_pos`
- [ ] `ObjectRef:set_properties`
- [ ] `ObjectRef:set_rotation`
- [ ] `ObjectRef:set_sprite`
- [ ] `ObjectRef:set_texture_mod`
- [ ] `ObjectRef:set_velocity`
- [ ] `ObjectRef:set_wielded_item`
- [ ] `ObjectRef:set_yaw`
</details>

<details><summary><code>PlayerRef</code></summary>

- [ ] `PlayerRef:add_player_velocity`
- [ ] `PlayerRef:get_attribute`
- [ ] `PlayerRef:get_breath`
- [ ] `PlayerRef:get_clouds`
- [ ] `PlayerRef:get_day_night_ratio`
- [ ] `PlayerRef:get_eye_offset`
- [ ] `PlayerRef:get_formspec_prepend`
- [ ] `PlayerRef:get_fov`
- [ ] `PlayerRef:get_inventory_formspec`
- [ ] `PlayerRef:get_local_animation`
- [ ] `PlayerRef:get_look_dir`
- [ ] `PlayerRef:get_look_horizontal`
- [ ] `PlayerRef:get_look_pitch`
- [ ] `PlayerRef:get_look_vertical`
- [ ] `PlayerRef:get_look_yaw`
- [ ] `PlayerRef:get_meta`
- [ ] `PlayerRef:get_moon`
- [ ] `PlayerRef:get_physics_override`
- [ ] `PlayerRef:get_player_control_bits`
- [ ] `PlayerRef:get_player_control`
- [ ] `PlayerRef:get_player_name`
- [ ] `PlayerRef:get_player_velocity`
- [ ] `PlayerRef:get_sky_color`
- [ ] `PlayerRef:get_sky`
- [ ] `PlayerRef:get_stars`
- [ ] `PlayerRef:get_sun`
- [ ] `PlayerRef:hud_add`
- [ ] `PlayerRef:hud_change`
- [ ] `PlayerRef:hud_get_flags`
- [ ] `PlayerRef:hud_get`
- [ ] `PlayerRef:hud_remove`
- [ ] `PlayerRef:hud_set_flags`
- [ ] `PlayerRef:hud_set_hotbar_image`
- [ ] `PlayerRef:hud_set_hotbar_itemcount`
- [ ] `PlayerRef:hud_set_hotbar_selected_image`
- [ ] `PlayerRef:override_day_night_ratio`
- [ ] `PlayerRef:send_mapblock`
- [ ] `PlayerRef:set_attribute`
- [ ] `PlayerRef:set_breath`
- [ ] `PlayerRef:set_clouds`
- [ ] `PlayerRef:set_eye_offset`
- [ ] `PlayerRef:set_formspec_prepend`
- [ ] `PlayerRef:set_fov`
- [ ] `PlayerRef:set_inventory_formspec`
- [ ] `PlayerRef:set_local_animation`
- [ ] `PlayerRef:set_look_horizontal`
- [ ] `PlayerRef:set_look_pitch`
- [ ] `PlayerRef:set_look_vertical`
- [ ] `PlayerRef:set_look_yaw`
- [ ] `PlayerRef:set_minimap_modes`
- [ ] `PlayerRef:set_moon`
- [ ] `PlayerRef:set_physics_override`
- [ ] `PlayerRef:set_sky`
- [ ] `PlayerRef:set_sky`
- [ ] `PlayerRef:set_stars`
- [ ] `PlayerRef:set_sun`
</details>

<details><summary><code>PcgRandom</code></summary>

- [ ] `PcgRandom`
- [ ] `PcgRandom:next`
- [ ] `PcgRandom:rand_normal_dist`
</details>

<details><summary><code>PerlinNoise</code></summary>

- [ ] `minetest.get_perlin`
- [ ] `PerlinNoise`
- [ ] `PerlinNoise:get_2d`
- [ ] `PerlinNoise:get_3d`
</details>

<details><summary><code>PerlinNoiseMap</code></summary>

- [ ] `minetest.get_perlin_map`
- [ ] `PerlinNoiseMap`
- [ ] `PerlinNoiseMap:calc_2d_map`
- [ ] `PerlinNoiseMap:calc_3d_map`
- [ ] `PerlinNoiseMap:get_2d_map_flat`
- [ ] `PerlinNoiseMap:get_2d_map`
- [ ] `PerlinNoiseMap:get_3d_map_flat`
- [ ] `PerlinNoiseMap:get_3d_map`
- [ ] `PerlinNoiseMap:get_map_slice`
</details>

<details><summary><code>PseudoRandom</code></summary>

- [ ] `PseudoRandom`
- [ ] `PseudoRandom:next`
</details>

<details><summary><code>Raycast</code> (done)</summary>

- [x] `Raycast`
- [x] `minetest.raycast`
- [x] `Raycast:next`
</details>

<details><summary><code>SecureRandom</code></summary>

- [ ] `SecureRandom`
- [ ] `SecureRandom:next_bytes`
</details>

<details><summary><code>Settings</code></summary>

- [ ] `Settings`
- [ ] `Settings:get_bool`
- [ ] `Settings:get_flags`
- [ ] `Settings:get_names`
- [ ] `Settings:get_np_group`
- [ ] `Settings:get`
- [ ] `Settings:remove`
- [ ] `Settings:set_bool`
- [ ] `Settings:set_np_group`
- [ ] `Settings:set`
- [ ] `Settings:to_table`
- [ ] `Settings:write`
</details>

<details><summary><code>VoxelArea</code> (done)</summary>

- [x] `VoxelArea:contains`
- [x] `VoxelArea:containsi`
- [x] `VoxelArea:containsp`
- [x] `VoxelArea:getExtent`
- [x] `VoxelArea:getVolume`
- [x] `VoxelArea:index`
- [x] `VoxelArea:indexp`
- [x] `VoxelArea:iter`
- [x] `VoxelArea:iterp`
- [x] `VoxelArea:position`
</details>

<details><summary><code>VoxelManip</code></summary>

- [ ] `minetest.get_voxel_manip`
- [ ] `VoxelManip`
- [ ] `VoxelManip:calc_lighting`
- [ ] `VoxelManip:get_data`
- [ ] `VoxelManip:get_emerged_area`
- [ ] `VoxelManip:get_light_data`
- [ ] `VoxelManip:get_node_at`
- [ ] `VoxelManip:get_param2_data`
- [ ] `VoxelManip:read_from_map`
- [ ] `VoxelManip:set_data`
- [ ] `VoxelManip:set_light_data`
- [ ] `VoxelManip:set_lighting`
- [ ] `VoxelManip:set_node_at`
- [ ] `VoxelManip:set_param2_data`
- [ ] `VoxelManip:update_liquids`
- [ ] `VoxelManip:update_map`
- [ ] `VoxelManip:was_modified`
- [ ] `VoxelManip:write_to_map`
</details>

## Other
<details><summary>Formspec Elements</summary>

- [ ] `anchor`
- [ ] `animated_image`
- [ ] `background`
- [ ] `background`
- [ ] `background9`
- [ ] `bgcolor`
- [ ] `box`
- [ ] `button`
- [ ] `button_exit`
- [ ] `checkbox`
- [ ] `container`
- [ ] `container_end`
- [ ] `dropdown`
- [ ] `dropdown`
- [ ] `field`
- [ ] `field`
- [ ] `field_close_on_enter`
- [ ] `formspec_version`
- [ ] `hypertext`
- [ ] `image`
- [ ] `image_button`
- [ ] `image_button`
- [ ] `image_button_exit`
- [ ] `item_image`
- [ ] `item_image_button`
- [ ] `label`
- [ ] `list`
- [ ] `list`
- [ ] `listcolors`
- [ ] `listcolors`
- [ ] `listcolors`
- [ ] `listring`
- [ ] `listring`
- [ ] `model`
- [ ] `no_prepend`
- [ ] `padding`
- [ ] `position`
- [ ] `pwdfield`
- [ ] `real_coordinates`
- [ ] `scroll_container`
- [ ] `scroll_container_end`
- [ ] `scrollbar`
- [ ] `scrollbaroptions`
- [ ] `set_focus`
- [ ] `size`
- [ ] `style`
- [ ] `style_type`
- [ ] `tabheader`
- [ ] `tabheader`
- [ ] `tabheader`
- [ ] `table`
- [ ] `tablecolumns`
- [ ] `tableoptions`
- [ ] `textarea`
- [ ] `textlist`
- [ ] `textlist`
- [ ] `tooltip`
- [ ] `tooltip`
- [ ] `vertlabel`
</details>

<details><summary>Texture Modifiers (done)</summary>

- [x] `[brighten`
- [x] `[colorize`
- [x] `[combine`
- [x] `[crack`
- [x] `[cracko`
- [x] `[inventorycube`
- [x] `[invert`
- [x] `[lowpart`
- [x] `[makealpha`
- [x] `[mask`
- [x] `[multiply`
- [x] `[noalpha`
- [x] `[opacity`
- [x] `[png`
- [x] `[resize`
- [x] `[sheet`
- [x] `[transform`
- [x] `[verticalframe`
</details>

**Comment by Wuzzy2** [comment]
Wait, do I understand this right that you want to duplicate lua_api.md into the Dev Wiki *again*?

If yes, then this is a terrible idea that must be shut down NOW. Redundancy is bad, because nobody will bother to eternally keep the Dev Wiki in sync with the "real" official documentation `lua_api.md`. The Dev Wiki had this before and basically because a source of misinformation because of this and only after a long fight the redundant pages were finally nuked. If the Lua API documentation is meant to appear in the documentation, then it should ideally grab its text from the actual source file rather than copy it once and then forget it forever.

If no, ignore my comment. XD

**Comment by GreenXenith** [comment]
> Wait, do I understand this right that you want to duplicate lua_api.md into the Dev Wiki again?

This issue is a result of merging https://github.com/minetest/minetest_docs with this repo. The eventual intent is to replace lua_api.md. This will be the "real" official documentation.
